extends Node
## Autoload: identity of the running build, the mount point for content packs,
## and the owner of the launcher configuration.
##
## Register this FIRST in the autoload list. A content pack has to be mounted
## before anything loads a scene or a script out of res://, and everything this
## node needs is captured into plain values while res:// is still guaranteed to
## be the binary's own content.

## The binary's build stamp, generated by ci/prepare_build.sh at this fixed path.
## preload() resolves at compile time, i.e. before any content pack is mounted,
## so it always describes the APK/EXE itself and never a pack shadowing it.
const BuildVersion := preload("res://build_version.gd")

## The launcher's own version, independent of the game's.
const LauncherVersion := preload("res://addons/launcher/launcher_version.gd")

## Project setting pointing at this game's LauncherConfig.
const CONFIG_PATH_SETTING := "launcher/config_path"
const DEFAULT_CONFIG_PATH := "res://launcher_config.tres"

const STATE_PATH := "user://update_state.json"
const CONTENT_DIR := "user://content"
const STAGING_DIR := "user://staging"
## How long a file this launcher left in staging may sit untouched before a launch removes it.
const STAGING_MAX_AGE_SECONDS := 86400

## Version of the APK/EXE. A manifest advertising a higher one cannot be
## satisfied by a content pack -- it needs a new binary.
var binary_version: int = 0
## Content version baked into the binary at build time.
var base_content_version: int = 0
## Content version actually live right now: the pack's if one is mounted,
## otherwise the binary's.
var content_version: int = 0
var version_name: String = ""
var commit: String = ""
var built_at: String = ""
var is_ci_build: bool = false
## Branch whose rolling prerelease this build follows, or "" for a normal build
## that follows /releases/latest/. Stamped in by ci/prepare_build.sh.
var release_branch: String = ""
## This build's own patch notes, baked in at build time so they are readable
## offline and before the first update check.
var own_changes: Array = []

## Absolute res-style path of the mounted pack, or "" when running stock content.
var active_pack_path: String = ""
## Non-empty when a staged pack was found but could not be mounted.
var pack_error: String = ""

## This game's launcher configuration. Never null -- falls back to defaults so a
## missing or broken config file degrades to a plain launcher instead of a crash.
var config: LauncherConfig = null


func _init() -> void:
	binary_version = BuildVersion.BINARY_VERSION
	base_content_version = BuildVersion.CONTENT_VERSION
	content_version = base_content_version
	version_name = BuildVersion.VERSION_NAME
	commit = BuildVersion.COMMIT
	built_at = BuildVersion.BUILT_AT
	is_ci_build = BuildVersion.IS_CI_BUILD
	release_branch = BuildVersion.RELEASE_BRANCH
	own_changes = BuildVersion.CHANGES.duplicate()

	_mount_staged_content()
	_sweep_staging_dir()
	# After mounting, so a content update can ship a new title or background.
	_load_config()


func _load_config() -> void:
	var path := str(ProjectSettings.get_setting(CONFIG_PATH_SETTING, DEFAULT_CONFIG_PATH))
	if ResourceLoader.exists(path):
		var loaded: Variant = load(path)
		if loaded is LauncherConfig:
			config = loaded
			return
		push_warning("[BuildInfo] %s is not a LauncherConfig; using defaults." % path)
	else:
		push_warning("[BuildInfo] No launcher config at %s; using defaults." % path)
	config = LauncherConfig.new()


## Mounts the staged content pack if there is one and it is genuinely newer than
## what the binary already ships.
func _mount_staged_content() -> void:
	var state := read_state()
	if state.is_empty():
		_sweep_content_dir("")
		return

	var staged_version := int(state.get("content_version", 0))
	var pack_path := str(state.get("pack_path", ""))

	if pack_path.is_empty() or not FileAccess.file_exists(pack_path):
		clear_state()
		_sweep_content_dir("")
		return

	# A pack staged by a build following a different release stream is not ours,
	# whatever its version says. A branch build and the release build are supposed
	# to have separate user:// directories, so this should be unreachable -- but
	# the consequence of mounting the wrong pack is the release app silently
	# running unreleased content, so it is checked rather than assumed. A game that
	# never sets a branch compares "" with "" and is unaffected.
	#
	# Absent on state written before this key existed, which can only be a release
	# build's own pack, and "" is what a release build expects.
	var staged_branch := str(state.get("branch", ""))
	if staged_branch != release_branch:
		pack_error = "Staged content pack belongs to a different build stream; discarding it."
		push_warning("[BuildInfo] %s (staged \"%s\", running \"%s\")" % [
			pack_error, staged_branch, release_branch])
		clear_state()
		_sweep_content_dir("")
		return

	# A binary update ships its own, newer content. Anything staged at or below
	# that is stale and must not be mounted, or it would roll content backwards.
	if staged_version <= base_content_version:
		print("[BuildInfo] Discarding stale content pack v%d (binary ships v%d)." % [
			staged_version, base_content_version])
		clear_state()
		_sweep_content_dir("")
		return

	var expected_size := int(state.get("size", -1))
	if expected_size >= 0:
		var probe := FileAccess.open(pack_path, FileAccess.READ)
		if probe == null or probe.get_length() != expected_size:
			pack_error = "Staged content pack is truncated or unreadable."
			push_warning("[BuildInfo] " + pack_error)
			clear_state()
			_sweep_content_dir("")
			return

	# The size above only catches a short file. The checksum was verified when the pack was
	# downloaded and recorded in the state; checking it again here is what makes that record a
	# guarantee rather than a claim. State written before the key existed, or without a value,
	# has nothing to compare with and still mounts.
	var expected_sha := str(state.get("sha256", "")).strip_edges().to_lower()
	if not expected_sha.is_empty() and FileAccess.get_sha256(pack_path).to_lower() != expected_sha:
		pack_error = "Staged content pack does not match its checksum; discarding it."
		push_warning("[BuildInfo] " + pack_error)
		clear_state()
		_sweep_content_dir("")
		return

	if ProjectSettings.load_resource_pack(pack_path, true):
		content_version = staged_version
		active_pack_path = pack_path
		print("[BuildInfo] Mounted content pack v%d from %s" % [staged_version, pack_path])
		# The mounted pack is held open; only sweep the others.
		_sweep_content_dir(pack_path)
	else:
		pack_error = "Content pack v%d failed to mount." % staged_version
		push_warning("[BuildInfo] " + pack_error)
		clear_state()
		_sweep_content_dir("")


## Deletes every pack in the content dir except [param keep_path]. Packs are
## named per-version so a freshly downloaded one never has to overwrite the one
## currently mounted -- which would fail outright on Windows, where a mounted
## pack stays locked for the life of the process.
func _sweep_content_dir(keep_path: String) -> void:
	var dir := DirAccess.open(CONTENT_DIR)
	if dir == null:
		return
	for file in dir.get_files():
		var full := CONTENT_DIR.path_join(file)
		if full == keep_path:
			continue
		dir.remove(file)


## Removes what a launch can prove is dead from [constant STAGING_DIR]. It cannot simply empty
## it: a second copy of the app may be downloading into it, an APK may still be open in the
## system installer, and the Windows helper script waits up to a minute for this process to
## exit before it copies update-N.exe. Two rules decide:
##  - update-N.apk / update-N.exe with N at or below this binary's own version: that update is
##    installed, so nothing will read the file again.
##  - anything else this launcher writes there (a .part, apply_update.ps1, an update for a
##    newer binary) once it has sat untouched for [constant STAGING_MAX_AGE_SECONDS]. A download
##    in progress keeps refreshing its file, and a good APK left by backing out of the
##    installer stays long enough to be reused instead of fetched again.
## Files this launcher does not recognise are left alone. [param now] is for tests.
func _sweep_staging_dir(now: int = -1) -> void:
	var dir := DirAccess.open(STAGING_DIR)
	if dir == null:
		return
	if now < 0:
		now = int(Time.get_unix_time_from_system())
	for file in dir.get_files():
		var update_version := _staged_update_version(file)
		if update_version < 0 and not file.ends_with(".part") and file != "apply_update.ps1":
			continue
		var installed := update_version >= 0 and update_version <= binary_version
		var modified := int(FileAccess.get_modified_time(STAGING_DIR.path_join(file)))
		# 0 means the time could not be read: keep the file rather than guess its age.
		var idle := modified > 0 and now - modified > STAGING_MAX_AGE_SECONDS
		if installed or idle:
			dir.remove(file)


## N for a file named update-N.apk or update-N.exe, otherwise -1.
func _staged_update_version(file: String) -> int:
	if not file.begins_with("update-") or file.get_extension() not in ["apk", "exe"]:
		return -1
	var number := file.get_basename().trim_prefix("update-")
	return int(number) if number.is_valid_int() and int(number) >= 0 else -1


func read_state() -> Dictionary:
	if not FileAccess.file_exists(STATE_PATH):
		return {}
	var file := FileAccess.open(STATE_PATH, FileAccess.READ)
	if file == null:
		return {}
	var parsed: Variant = JSON.parse_string(file.get_as_text())
	return parsed if parsed is Dictionary else {}


func write_state(state: Dictionary) -> bool:
	var file := FileAccess.open(STATE_PATH, FileAccess.WRITE)
	if file == null:
		push_warning("[BuildInfo] Could not write %s" % STATE_PATH)
		return false
	file.store_string(JSON.stringify(state, "\t"))
	return true


func clear_state() -> void:
	if FileAccess.file_exists(STATE_PATH):
		DirAccess.remove_absolute(STATE_PATH)


## "android", "windows", "linux", "macos", "web" or the lowercased OS name.
func platform_key() -> String:
	match OS.get_name():
		"Android": return "android"
		"Windows", "UWP": return "windows"
		"Linux", "FreeBSD", "NetBSD", "OpenBSD", "BSD": return "linux"
		"macOS": return "macos"
		"Web": return "web"
		_: return OS.get_name().to_lower()


func is_android() -> bool:
	return OS.get_name() == "Android"


## Human-readable stamp for the corner of the launcher: the game on the first
## line, the launcher it is running on the second.
func display_version() -> String:
	var text := "v%s  ·  bin %d  ·  content %d" % [version_name, binary_version, content_version]
	if not commit.is_empty() and commit != "local":
		text += "  ·  %s" % commit
	# First, and named, because a branch build is otherwise indistinguishable from
	# the app the player has -- and the whole point is that it is not that app.
	if not release_branch.is_empty():
		text = "branch %s  ·  " % release_branch + text
	return text + "\n" + launcher_version()


## Repository this launcher was synced from, or "" inside the template itself.
func launcher_source() -> String:
	return LauncherVersion.SOURCE


## "launcher <semver> · <template commit>", for bug reports.
##
## COMMIT defaults to "local" rather than "", so the is_empty() test this used to
## make could never fire, and the demo rendered "launcher 1.0.0  ·  local" -- the
## same sentinel display_version() suppresses one line above. Both tests are kept:
## a hand-edited copy can leave it empty.
##
## This reports the launcher the BINARY shipped. After a content pack mounts, the
## launcher code actually running is the pack's, which can be a different version.
## Closing that is a bigger change than #34 asked for; it is filed separately.
func launcher_version() -> String:
	var text := "launcher %s" % LauncherVersion.VERSION
	if not LauncherVersion.COMMIT.is_empty() and LauncherVersion.COMMIT != "local":
		text += "  ·  %s" % LauncherVersion.COMMIT
	return text
